---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: scratchpad-pr
spec:
  params:
    - name: repo_url
    - name: revision
  workspaces:
  - name: source
  tasks:
    - name: fetch
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)
      workspaces:
      - name: output
        workspace: source
    - name: test
      runAfter: [fetch]
      taskRef:
        name: golang-test
      params:
        - name: package
          value: "github.com/chmouel/go-rest-api-test"
        - name: packages
          value: "./pkg/..."
      workspaces:
        - name: source
          workspace: source
    - name: lint
      runAfter: [fetch]
      taskRef:
        name: golangci-lint
      params:
        - name: package
          value: "."
        - name: flags
          value: "-v --timeout 15m"
        - name: version
          value: v1.24.0
      workspaces:
        - name: source
          workspace: source
